version: '3.9'
services:
    postgresql:
        stop_grace_period: 3s
        restart: unless-stopped
        env_file:
            - .env
        build:
            context: .
            target: postgresql
            args:
                - password=${PSQL_PASSWORD}
                - database=${PSQL_DATABASE}
        # volumes:
        #     - "./containers/postgresql/log:/var/log/postgresql"
        #     - "./containers/postgresql/data:/var/lib/postgresql"
        networks:
            - backend
        expose:
            - 5432
    backend:
        command: bash -c 'yarn install && yarn run start:dev'
        stop_grace_period: 3s
        depends_on:
            - postgresql
        restart: unless-stopped
        env_file:
            - .env
        build:
            context: .
            target: backend
        volumes:
            - ./NJMPU-API:/app
        networks:
            - backend
            - frontend
        expose:
            - 3000
    frontend:
        command: bash -c 'yarn install && yarn run dev --host'
        stop_grace_period: 3s
        depends_on:
            - backend
        restart: unless-stopped
        build:
            context: .
            target: frontend
        volumes:
            - ./NJMPU-FRONT:/app
        networks:
            - backend
            - frontend
        expose:
            - 5000
    nginx:
        command: bash -c 'nginx -g "daemon off;"'
        stop_grace_period: 3s
        depends_on:
            - frontend
        restart: unless-stopped
        build:
            context: .
            target: frontend
        volumes:
            - ./NJMPU-API/shared:/app/dist/pictures:r
            - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf:r
            - ./Docker/nginx/app.dev.conf:/etc/nginx/sites-enabled/default:r
            - ./Docker/nginx/log:/var/log/nginx
        networks:
            - backend
            - frontend
        expose:
            - 443
        ports:
            - 443:443

networks:
    backend:
        internal: true
    frontend:
